import {
  PermisoAccionEnum,
  PermisoModeloEnum,
  PermisoModuloEnum,
} from 'src/app/enums/permiso-enum';

export interface Permiso {
  id: number;
  accion: PermisoAccionEnum;
  modelo: PermisoModeloEnum;
  modulo: PermisoModuloEnum;
  modelo_titulo: string;
  checked: boolean; // <- campo auxiliar que solo se utiliza en el front
  descripcion: string;
  is_for_superuser: boolean;
}

export const mockPermisoList: Permiso[] = [
  {
    id: 1,
    accion: PermisoAccionEnum.VER,
    modelo: PermisoModeloEnum.USER,
    modelo_titulo: PermisoModeloEnum.USER,
    modulo: PermisoModuloEnum.USUARIOS,
    checked: true,
    descripcion: 'Ver usuario',
    is_for_superuser: false,
  },
  {
    id: 2,
    accion: PermisoAccionEnum.REPORTE,
    modelo: PermisoModeloEnum.CENTRO_OPERATIVO,
    modelo_titulo: PermisoModeloEnum.CENTRO_OPERATIVO,
    modulo: PermisoModuloEnum.ENTIDADES,
    checked: true,
    descripcion: 'Reporte de Centro Operativo',
    is_for_superuser: false,
  },
  {
    id: 3,
    accion: PermisoAccionEnum.REPORTE,
    modelo: PermisoModeloEnum.GESTOR_CARGA,
    modelo_titulo: PermisoModeloEnum.GESTOR_CARGA,
    modulo: PermisoModuloEnum.ENTIDADES,
    checked: true,
    descripcion: 'Reporte de Gestor de Carga',
    is_for_superuser: true,
  },
  {
    id: 4,
    accion: PermisoAccionEnum.REPORTE,
    modelo: PermisoModeloEnum.PROVEEDOR,
    modelo_titulo: PermisoModeloEnum.PROVEEDOR,
    modulo: PermisoModuloEnum.ENTIDADES,
    checked: true,
    descripcion: 'Reporte de Proveedor',
    is_for_superuser: false,
  },
  {
    id: 5,
    accion: PermisoAccionEnum.REPORTE,
    modelo: PermisoModeloEnum.PUNTO_VENTA,
    modelo_titulo: PermisoModeloEnum.PUNTO_VENTA,
    modulo: PermisoModuloEnum.ENTIDADES,
    checked: true,
    descripcion: 'Reporte de Punto de Venta',
    is_for_superuser: false,
  },
  {
    id: 6,
    accion: PermisoAccionEnum.REPORTE,
    modelo: PermisoModeloEnum.REMITENTE,
    modelo_titulo: PermisoModeloEnum.REMITENTE,
    modulo: PermisoModuloEnum.ENTIDADES,
    checked: true,
    descripcion: 'Reporte de Remitente',
    is_for_superuser: false,
  },
  {
    id: 7,
    accion: PermisoAccionEnum.LISTAR,
    modelo: PermisoModeloEnum.PUNTO_VENTA,
    modelo_titulo: PermisoModeloEnum.PUNTO_VENTA,
    modulo: PermisoModuloEnum.ENTIDADES,
    checked: true,
    descripcion: 'Crear Punto de Venta',
    is_for_superuser: false,
  },
  {
    id: 8,
    accion: PermisoAccionEnum.CREAR,
    modelo: PermisoModeloEnum.PUNTO_VENTA,
    modelo_titulo: PermisoModeloEnum.PUNTO_VENTA,
    modulo: PermisoModuloEnum.ENTIDADES,
    checked: true,
    descripcion: 'Crear Punto de Venta',
    is_for_superuser: false,
  },
  {
    id: 9,
    accion: PermisoAccionEnum.REPORTE,
    modelo: PermisoModeloEnum.PROPIETARIO,
    modelo_titulo: PermisoModeloEnum.PROPIETARIO,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Reporte de Propietario',
    is_for_superuser: false,
  },
  {
    id: 10,
    accion: PermisoAccionEnum.REPORTE,
    modelo: PermisoModeloEnum.CAMION,
    modelo_titulo: PermisoModeloEnum.CAMION,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Reporte de Camion',
    is_for_superuser: false,
  },
  {
    id: 11,
    accion: PermisoAccionEnum.REPORTE,
    modelo: PermisoModeloEnum.CHOFER,
    modelo_titulo: PermisoModeloEnum.CHOFER,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Reporte de Chofer',
    is_for_superuser: false,
  },
  {
    id: 12,
    accion: PermisoAccionEnum.REPORTE,
    modelo: PermisoModeloEnum.SEMIRREMOLQUE,
    modelo_titulo: PermisoModeloEnum.SEMIRREMOLQUE,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Reporte de Semirremolque',
    is_for_superuser: false,
  },
  {
    id: 13,
    accion: PermisoAccionEnum.CREAR,
    modelo: PermisoModeloEnum.CHOFER,
    modelo_titulo: PermisoModeloEnum.CHOFER,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Crear de Chofer',
    is_for_superuser: false,
  },
  {
    id: 14,
    accion: PermisoAccionEnum.EDITAR,
    modelo: PermisoModeloEnum.CHOFER,
    modelo_titulo: PermisoModeloEnum.CHOFER,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Editar de Chofer',
    is_for_superuser: false,
  },
  {
    id: 15,
    accion: PermisoAccionEnum.VER,
    modelo: PermisoModeloEnum.CHOFER,
    modelo_titulo: PermisoModeloEnum.CHOFER,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Ver de Chofer',
    is_for_superuser: false,
  },
  {
    id: 16,
    accion: PermisoAccionEnum.CREAR,
    modelo: PermisoModeloEnum.PROPIETARIO,
    modelo_titulo: PermisoModeloEnum.PROPIETARIO,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Crear de Propietario',
    is_for_superuser: false,
  },
  {
    id: 17,
    accion: PermisoAccionEnum.EDITAR,
    modelo: PermisoModeloEnum.PROPIETARIO,
    modelo_titulo: PermisoModeloEnum.PROPIETARIO,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Editar de Propietario',
    is_for_superuser: false,
  },
  {
    id: 18,
    accion: PermisoAccionEnum.VER,
    modelo: PermisoModeloEnum.PROPIETARIO,
    modelo_titulo: PermisoModeloEnum.PROPIETARIO,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Ver de Propietario',
    is_for_superuser: false,
  },
  {
    id: 19,
    accion: PermisoAccionEnum.CREAR,
    modelo: PermisoModeloEnum.CAMION,
    modelo_titulo: PermisoModeloEnum.CAMION,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Crear de Camión',
    is_for_superuser: false,
  },
  {
    id: 20,
    accion: PermisoAccionEnum.EDITAR,
    modelo: PermisoModeloEnum.CAMION,
    modelo_titulo: PermisoModeloEnum.CAMION,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Editar de Camión',
    is_for_superuser: false,
  },
  {
    id: 21,
    accion: PermisoAccionEnum.LISTAR,
    modelo: PermisoModeloEnum.CAMION,
    modelo_titulo: PermisoModeloEnum.CAMION,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Listar de Camión',
    is_for_superuser: false,
  },
  {
    id: 22,
    accion: PermisoAccionEnum.CREAR,
    modelo: PermisoModeloEnum.SEMIRREMOLQUE,
    modelo_titulo: PermisoModeloEnum.SEMIRREMOLQUE,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Crear de Semi-remolque',
    is_for_superuser: false,
  },
  {
    id: 23,
    accion: PermisoAccionEnum.EDITAR,
    modelo: PermisoModeloEnum.SEMIRREMOLQUE,
    modelo_titulo: PermisoModeloEnum.SEMIRREMOLQUE,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Editar de Semi-remolque',
    is_for_superuser: false,
  },
  {
    id: 24,
    accion: PermisoAccionEnum.LISTAR,
    modelo: PermisoModeloEnum.SEMIRREMOLQUE,
    modelo_titulo: PermisoModeloEnum.SEMIRREMOLQUE,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Listar de Semi-remolque',
    is_for_superuser: false,
  },
  {
    id: 25,
    accion: PermisoAccionEnum.CAMBIAR_ESTADO,
    modelo: PermisoModeloEnum.CAMION,
    modelo_titulo: PermisoModeloEnum.CAMION,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Cambiar estado de Camión',
    is_for_superuser: false,
  },
  {
    id: 26,
    accion: PermisoAccionEnum.CAMBIAR_ESTADO,
    modelo: PermisoModeloEnum.CHOFER,
    modelo_titulo: PermisoModeloEnum.CHOFER,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Cambiar estado de Chofer',
    is_for_superuser: false,
  },
  {
    id: 27,
    accion: PermisoAccionEnum.CAMBIAR_ESTADO,
    modelo: PermisoModeloEnum.PROPIETARIO,
    modelo_titulo: PermisoModeloEnum.PROPIETARIO,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Cambiar estado de Propietario',
    is_for_superuser: false,
  },
  {
    id: 28,
    accion: PermisoAccionEnum.CAMBIAR_ESTADO,
    modelo: PermisoModeloEnum.SEMIRREMOLQUE,
    modelo_titulo: PermisoModeloEnum.SEMIRREMOLQUE,
    modulo: PermisoModuloEnum.FLOTA,
    checked: true,
    descripcion: 'Cambiar estado de Semi-remolque',
    is_for_superuser: false,
  },
];
