export enum EstadoEnum {
  ACTIVO = 'Activo',
  ACEPTADO = 'Aceptado',
  ANULADO = 'Anulado',
  CANCELADO = 'Cancelado',
  CONCILIADO = 'Conciliado',
  CONFIRMADO = 'Confirmado',
  CONTABILIZADO = 'Contabilizado',
  ELIMINADO = 'Eliminado',
  EN_PROCESO = 'En Proceso',
  EN_REVISION = 'En Revisión',
  FINALIZADO = 'Finalizado',
  LIQUIDADO = 'Liquidado',
  INACTIVO = 'Inactivo',
  NUEVO = 'Nuevo',
  PENDIENTE = 'Pendiente',
}
