export enum MarcaCamionEnum {
  LUMAVIT = 'LUMAVIT',
  MERCEDES_BENZ = 'MERCEDES BENZ',
  METALURGICA_GUTIERREZ = 'METALURGICA GUTIERREZ',
  PHOENIX = 'PHOENIX',
  SCANIA = 'SCANIA',
  TECNO_EQUIPO = 'TECNO EQUIPO',
  VOLVO = 'VOLVO',
}
