export enum MarcaSemiEnum {
  GUERRA = 'GUERRA',
  LIBRELATO = 'LIBRELATO',
  LUMAVIT = 'LUMAVIT',
  METALURGICA_GUTIERREZ = 'METALURGICA GUTIERREZ',
  NOMA = 'NOMA',
  PHOENIX = 'PHOENIX',
  RANDON = 'RANDON',
  RODOVALE = 'RODOVALE',
  TECNO_EQUIPO = 'TECNO EQUIPO',
}
