export enum PermisoAccionEnum {
  CREAR = "crear",
  EDITAR = "editar",
  ELIMINAR = "eliminar",
  LISTAR = "listar",
  MODIFICAR_CONTACTOS = "modificar_contactos",
  MODIFICAR_ALIAS = "modificar_alias",
  VER = "ver",
  REPORTE = "reporte",
}

export enum PermisoModeloEnum {
  CAMION = "camion",
  CARGO = "cargo",
  CENTRO_OPERATIVO_CLASIFICACION = "centro_operativo_clasificacion",
  CENTRO_OPERATIVO = "centro_operativo",
  CHOFER = "chofer",
  CIUDAD = "ciudad",
  COLOR = "color",
  COMPOSICION_JURIDICA = "composicion_juridica",
  CONTACTO = "contacto",
  ENTE_EMISOR_AUTOMOTOR = "ente_emisor_automotor",
  ENTE_EMISOR_TRANSPORTE = "ente_emisor_transporte",
  GESTOR_CARGA = "gestor_carga",
  LOCALIDAD = "localidad",
  MARCA_CAMION = "marca_camion",
  MARCA_SEMI = "marca_semi",
  MONEDA = "moneda",
  PAIS = "pais",
  PERMISO = "permiso",
  PROPIETARIO = "propietario",
  PROVEEDOR = "proveedor",
  PUNTO_VENTA = "punto_venta",
  REMITENTE = "remitente",
  ROL = "rol",
  SEMIRREMOLQUE = "semirremolque",
  SEMI_CLASIFICACION = "semi_clasificacion",
  TIPO_CAMION = "tipo_camion",
  TIPO_CARGA = "tipo_carga",
  TIPO_DOCUMENTO = "tipo_documento",
  TIPO_PERSONA = "tipo_persona",
  TIPO_REGISTRO = "tipo_registro",
  TIPO_SEMI = "tipo_semi",
  USER = "usuario",
}
